### ISSUE TITLE
Function Request: Add LawnStrings Conversion

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen#10]
There are three types of LawnStrings in PvZ 2 International:
TXT: 1.0 - 6.7
JSON-Map: 6.8 - 8.5
JSON-List: 8.6 - current

Make a function that can convert between these three. Remember that the TXT one has UTF-16 LE BOM. And when converted to JSON, it must have "version": 1 at the end

**Comment by harumazzz** [comment]
I will try to add the support for this issue. Here is what I have to do:
- Convert text to json map (6.9 -> 8.2) ✔
- Convert text to json text (8.3 -> now) ✔
- Convert json map to text ✔
- Convert json map to json text ✔
- Convert json text to text ✔
- Convert json text to json map ✔

I will be doing this issue slowly, but it should be in the next version.

**Comment by harumazzz** [comment]
The new version of script and shell has fully added the support for PvZ2 Lawnstrings. Please report any bugs in the future if you occur, I will close this as completed for now.
![image](https://github.com/Haruma-VN/Sen/assets/114157573/cdb96126-22b3-464c-95d3-4d91d78688c2)

**Comment by harumazzz** [comment]
The new version of shell and script also added the support for PvZ2 Chinese Lawnstring, it is currently support all type of PvZ2 Lawnstrings now.
![image](https://github.com/Haruma-VN/Sen/assets/114157573/bfb9c471-407e-495d-9845-6d7596659606)
![image](https://github.com/Haruma-VN/Sen/assets/114157573/9720e751-1df1-4bb5-bb48-075fb2ac2246)

**Comment by harumazzz** [comment]
Additionally, when the user convert lawnstrings with Sen, the tool will need to give them to know the file encoding type input and output so the user can know what to do next.
![image](https://github.com/Haruma-VN/Sen/assets/114157573/a5bf415c-afc8-4fc7-b897-b8a28a6a2355)
