### ISSUE TITLE
Function request: Add Image Senquence to Pam

### ISSUE THREAD

**Issue by sarahlydia9868** [Haruma-VN/Sen#11]
Make the function creates Pam by frames from image senquence.
Args: can adjust the size, move left, right, down, up.

**Comment by harumazzz** [comment]
I will try to add the support for image sequences to pam in the future.

**Comment by Haruma-VN** [comment]
I will try to add the support for image sequences to pam in the future.

**Comment by harumazzz** [comment]
Latest push has added this,
