### ISSUE TITLE
Script Request: Res Beautify

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen#12]
Make a script that will sort order of "slot", "path",... and rewrite slot number (to 0 as default). Using for RESOURCES.json

**Comment by harumazzz** [comment]
I will try to adapt it in the next version of Script

**Comment by harumazzz** [comment]
The new version of script has added the support for reorganizing resources. I will close this issue as completed now.
![image](https://github.com/Haruma-VN/Sen/assets/114157573/6e47849d-8dcd-4787-aa91-c6a0c90a3a36)
