### ISSUE TITLE
Q: ES6 标准 

### ISSUE THREAD

**Issue by welt007n** [Haruma-VN/Sen#15]
脚本遵循 ES6 标准吗？我不了解 Sen 项目中的 JS。

**Comment by harumazzz** [comment]
Sen 跟随 ES6 的标准，加和 Shell API 所以这会出现随机的指令。你不应该看JS，你应该 clone 这个项目，看項目內的 typescript 文件

**Comment by harumazzz** [comment]
如果您没有其他问题，请将此问题视为已解决。

**Comment by welt007n** [comment]
SEN 使用 JS 作为 API 调用？在一些源代码中是这样的
```ts
Sen.Shell.PvZ2Shell.RSBUnpack(inRSB, outDirectory);
```
如何知道要调用哪些函数？在您回答这个问题后，我将以已完成为由关闭此问题。

**Comment by harumazzz** [comment]
你可以在typescript文件中的声明中查看其他函数，也可以在其他JS中查看其他脚本函数

**Comment by welt007n** [comment]
谢谢老板的助理！
