### ISSUE TITLE
Function Request: 解码 PTX PvZ-Free

### ISSUE THREAD

**Issue by welt007n** [Haruma-VN/Sen#16]
请支持 PvZ-Free PTX 解码, 它们被发现存在于 PvZ-Free RSB
![image](https://github.com/Haruma-VN/Sen/assets/70569329/ffa31b27-7067-4ff0-800e-ec583f642301)

**Comment by harumazzz** [comment]
Sen 已经支持 PvZ-Free PTX 格式，您需要从 manifest.json 中获取信息
![image](https://github.com/Haruma-VN/Sen/assets/114157573/edc98b0b-1830-4af5-b86a-76c9c62c453e)
然后运行 PopCap PTX 解码功能，之后就能获得所需的 PNG 文件了
![image](https://github.com/Haruma-VN/Sen/assets/114157573/dc406cfc-5f94-4d53-b0bf-0b7daded2850)
如果您没有其他问题，请将此问题视为已解决。

**Comment by welt007n** [comment]
谢谢大佬！
