### ISSUE TITLE
Script Request: Convert 2c Res to 2i

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen#17]
Convert PvZ 2 Chinese Res to PvZ 2 International Res by fixing the different path compared to ID of sprites. Convert "origpath" to "path" then delete the "origpath".

**Comment by harumazzz** [comment]
[RepairPvZ2COrigPath.zip](https://github.com/Haruma-VN/Sen/files/13247791/RepairPvZ2COrigPath.zip)
