### ISSUE TITLE
Bug: 新旧工具问题

### ISSUE THREAD

**Issue by welt007n** [Haruma-VN/Sen#20]
老板，用您的旧工具（TRE）打包的 OBB 在用新工具（SEN）解包时总是出现 "Invalid RSG Compression Flag"的异常。我怎样才能解决这个问题，从而最终搬到 SEN，谢谢！

**Comment by harumazzz** [comment]
能否提供您的 RSB 以供测试？

**Comment by harumazzz** [comment]
在 Sen 的最新版本中，我更新了 RSB 解包松散约束，请在下一个版本中使用。
