### ISSUE TITLE
Function Request: Add support for Reanim in PvZ

### ISSUE THREAD

**Issue by sarahlydia9868** [Haruma-VN/Sen#26]
Add the support this file, decode and encode for reanim in pvz pc and pvz free.
[compiled.zip](https://github.com/Haruma-VN/Sen/files/12416545/compiled.zip)

**Comment by harumazzz** [comment]
Latest push has support this. Please close this issue as completed after you check the latest commit: [https://github.com/Haruma-VN/Sen/commit/bcc00f6984e9474c2070461afc29a4c75cafc3b8](https://github.com/Haruma-VN/Sen/commit/bcc00f6984e9474c2070461afc29a4c75cafc3b8?fbclid=IwAR2CdqXkQSrA75iNlVG_ItUJ2i8OP_STaMmj1K8GJyunJFxbS-5cVV_-mhQ)
