### ISSUE TITLE
Enable Resources Merging when Pack

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen#29]
Enable auto merging Resources when using PopCap RSB: Pack (Simple)

**Comment by harumazzz** [comment]
Unnecessary.

**Comment by harumazzz** [comment]
Replace the script in Scripts\Modules\Support\PopCap\PvZ2\RSB\Pack.js with this script and close this issue.

[Pack.zip](https://github.com/Haruma-VN/Sen/files/12643177/Pack.zip)
