### ISSUE TITLE
[Engine] Building to Android doesn't create libInternal.so

### ISSUE THREAD

**Issue by IceandFire04** [Haruma-VN/Sen#32]
Considering how you've made the project, you know this is vital. I would use an APK editor to move the old libInternal from the pre-built one in releases, although the current version of the engine branch has new features in it like .smf decompressing, so it wouldn't work anyway.

**Comment by harumazzz** [comment]
Compile the Internal by reading the readme, and then put it inside `Engine/android/app/src/main/jniLibs/arm64-v8a` then later build the APK with `flutter build apk`

**Comment by IceandFire04** [comment]
Do you know how to set NDK as my compiler/where to put it because it says that's what I'm missing

**Comment by harumazzz** [comment]
read cmake documentation

**Comment by IceandFire04** [comment]
Still couldn't find out how to do it (clang is located at C:\Program Files\LLVM\bin\clang.exe, NDK at C:\Users\gatli\android-ndk-r26b). Changed env variables, tried extra args, etc. Anything else I can try?

**Comment by harumazzz** [comment]
You need to use Android Studio clang to compile it, it's not LLVM. You just need to pick the compiler from CMake GUI and generate project (ninja)

**Comment by IceandFire04** [comment]
for whatever reason it just wont build for me. maybe you could just update the files under engine in releases 🤷

**Comment by IceandFire04** [comment]
Guess not
