### ISSUE TITLE
PvZ2C rsb unable to pack due to 2gb limit

### ISSUE THREAD

**Issue by Bobotka** [Haruma-VN/Sen#34]
Recently the .rsb of pvz2c on iOS has exceeded 2GB, which Sen and Tre are unable to pack due to the limit set to 2gb max. Is there any solution to this?

The versions the rsb exceeds the 2gb limit is 3.3.4 and above

**Comment by ThePrimalPea** [comment]
This issue is fixed in Sen 4

**Comment by harumazzz** [comment]
Please use this project instead: https://github.com/Haruma-VN/Sen.Environment
