### ISSUE TITLE
Sen does not display anything when dragging the obb file

### ISSUE THREAD

**Issue by Erwan888** [Haruma-VN/Sen#35]
I downloaded shell. I installed it, it tells me this during installation : 
"$ Internal Module not found, redownloading Internal from Github 
$ Script Module not found, redownloading Script from Github "
then my pc indicates that Sen is installed. But when I drag the obb file in Sen, it doesn't show me anything

**Comment by IceandFire04** [comment]
It has to have .RSB at the end so you just have to rename it
Then it'll show you what you can do with it

**Comment by harumazzz** [comment]
Are you sure? Can you run sen with administrator permission?

**Comment by Erwan888** [comment]
Even if i run sen with administrator permission, it display nothing after
Do I need to install something extra on my PC just in case?

**Comment by harumazzz** [comment]
Can you record a video?

**Comment by Erwan888** [comment]
while I was doing the record I opened sen to show the install and everything, and it had no more problems. So sorry for the inconvenience

**Comment by harumazzz** [comment]
If you have no more issue or question please close this issue as completed.
