### ISSUE TITLE
"content://com.android.providers.downloads.documents/document/msf%3A1000090150"

### ISSUE THREAD

**Issue by Frostybtfindingscript** [Haruma-VN/Sen#36]
Hello, im submitting this issue because i was trying to decode stuff then i picked a json and said "content://com.android.providers.downloads.documents/document/msf%3A1000090150" photos are below.
![Screenshot_20240810-151407](https://github.com/user-attachments/assets/c8480e54-a14f-498a-afbd-7bceaffd3ae8)
Please help ASAP.

**Comment by IceandFire04** [comment]
`content://` paths don't work. You may have to use a different file explorer or select a file from where you can see the `android` directory

Also, paths with the percents don't work either

**Comment by harumazzz** [comment]
Pick a File Manager not default one from Android.
