### ISSUE TITLE
Improve: Add strict for "pitch" in manifest

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen#8]
Make if the "pitch" of that rsg is invalid in manifest, packing rsb won't work. The tool will detect that if the "pitch" doesn't have an exact number of mutiply 4 by "width", it will stop packing. Apply to these texture formats: 0, 30, 147.

**Comment by harumazzz** [comment]
I will try to add the strict enhancement in the tool next version.

**Comment by harumazzz** [comment]
The new version of script has implement this error. I will close this as complete for now.
![image](https://github.com/Haruma-VN/Sen/assets/114157573/de825962-466a-474d-8126-5c31d2e5a0ce)
