### ISSUE TITLE
Function Request: Add Split and Merge for Manifest

### ISSUE THREAD

**Issue by ThePrimalPea** [Haruma-VN/Sen#9]
The work with manifest.json could be done faster with splitting and merging

**Comment by harumazzz** [comment]
I will try to add the support for manifest split/merge in the future

**Comment by harumazzz** [comment]
The new version of script has added the support for this issue, I will close it as completed now.
![image](https://github.com/Haruma-VN/Sen/assets/114157573/d232d291-f57b-4fc6-8ab7-d3793b5f5bfa)
![image](https://github.com/Haruma-VN/Sen/assets/114157573/c28df67d-577e-4425-aa11-16fa5a42bebe)
